import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Eskom Application</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen w-screen bg-black'>
        <h1>I Like Cock</h1>
      </div>
    </>
  );
};

export default Home;
